base_url = "https://chaostreff-backnang.de"
author = "Chaostreff Backnang e.V."
compile_sass = false
minify_html = true
hard_link_static = true
title = "Chaostreff Backnang"
default_language = "de"

[markdown]
external_links_target_blank = true
smart_punctuation = true

[languages.en]
title = "Chaostreff Backnang"
